name: Update Solved Count Badge

on:
  push:
    paths:
      - 'problems/**.py'
  workflow_dispatch:

jobs:
  count_solutions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Count solved problems
        id: count
        run: |
          count=$(find problems -type f -name "*.py" | wc -l)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Generate badge
        uses: emibcn/badge-action@v2
        with:
          label: "Solved Problems"
          status: "${{ steps.count.outputs.count }}"
          color: blue
          path: "badge.svg"

      - name: Commit badge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add badge.svg
          git commit -m "Update badge" || echo "No changes"
          git push